// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Products.Infrastructure;

#nullable disable

namespace Products.Infrastructure.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20220303154240_init-db")]
    partial class initdb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Products.Domain.Categories.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("BannerUrl")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("https://via.placeholder.com/500x100.png");

                    b.Property<DateTime>("CreationDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2022, 3, 3, 15, 42, 39, 841, DateTimeKind.Utc).AddTicks(694));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("https://via.placeholder.com/85.png");

                    b.Property<DateTime>("ModificationDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2022, 3, 3, 15, 42, 39, 841, DateTimeKind.Utc).AddTicks(885));

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Permalink")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("https://via.placeholder.com/150x150.png");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = false,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Aliquip Lorem deserunt cupidatat deserunt sit qui excepteur. Ea aliquip eu irure et fugiat esse sit duis ad cillum mollit. Consectetur exercitation qui ea mollit enim ipsum excepteur. In velit aliqua adipisicing velit non in nisi commodo cupidatat Lorem voluptate labore. Enim cillum do ullamco proident ullamco ex Lorem consequat elit veniam sunt minim Lorem.\r\n",
                            ModificationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Permalink = "Lancaster-Greene",
                            Priority = 4,
                            Title = "Baird Moreno"
                        },
                        new
                        {
                            Id = 2,
                            Active = false,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Adipisicing in aliquip duis excepteur laborum ullamco commodo duis consectetur elit labore sint. Eiusmod duis esse ex deserunt ipsum id adipisicing occaecat veniam proident ad. Occaecat officia enim eu laboris et in nulla nulla voluptate ad. Ullamco eiusmod reprehenderit amet ad enim. Sit Lorem cillum consectetur amet minim officia nulla. Ex ipsum Lorem consequat adipisicing.\r\n",
                            ModificationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Permalink = "Bullock-Odonnell",
                            Priority = 1,
                            Title = "Carr Simmons"
                        },
                        new
                        {
                            Id = 3,
                            Active = false,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Reprehenderit nisi anim irure irure officia laborum incididunt anim. Laborum laborum adipisicing adipisicing incididunt velit labore dolor ut. Consectetur culpa ut nisi officia excepteur reprehenderit ad eu consequat voluptate sint.\r\n",
                            ModificationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Permalink = "Walker-Rose",
                            Priority = 3,
                            Title = "Barrera Hogan"
                        },
                        new
                        {
                            Id = 4,
                            Active = false,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ullamco est eiusmod sint laboris elit esse. Adipisicing minim dolore irure ut tempor culpa non consequat nostrud Lorem mollit aliquip. Aliquip nisi Lorem laborum nostrud eiusmod nisi anim officia eiusmod anim culpa. Qui elit cillum id eiusmod.\r\n",
                            ModificationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Permalink = "Karyn-Mccullough",
                            Priority = 2,
                            Title = "Carrillo Maddox"
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Pariatur proident eu velit consectetur ullamco. Velit do esse magna esse proident incididunt laborum elit enim occaecat incididunt anim fugiat. Lorem deserunt adipisicing excepteur et. Dolor officia et in ex id fugiat. Culpa elit ullamco enim eu amet pariatur eiusmod do.\r\n",
                            ModificationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Permalink = "Keith-Underwood",
                            Priority = 1,
                            Title = "Mccray Hoover"
                        },
                        new
                        {
                            Id = 6,
                            Active = true,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "In culpa commodo Lorem reprehenderit consectetur consectetur. Esse elit exercitation enim non mollit ea deserunt nisi nostrud consequat labore duis proident. Fugiat sint mollit Lorem quis voluptate reprehenderit tempor ut velit elit amet. Deserunt veniam officia incididunt reprehenderit.\r\n",
                            ModificationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = 1,
                            Permalink = "Kris-Schultz",
                            Priority = 5,
                            Title = "Nelson Mckinney"
                        },
                        new
                        {
                            Id = 7,
                            Active = true,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Dolor qui ad exercitation in anim proident aliquip consectetur. Eu eiusmod laboris proident reprehenderit reprehenderit anim exercitation dolore culpa occaecat eu nostrud eiusmod sunt. Occaecat deserunt ullamco occaecat non cillum tempor. Cupidatat sint ad ipsum elit ad mollit exercitation. Esse aliquip sunt proident laborum cillum esse nulla do mollit. Laborum est veniam veniam occaecat tempor laboris qui do elit incididunt. Nulla aliquip cupidatat ex voluptate eu id sint aliquip incididunt enim.\r\n",
                            ModificationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = 2,
                            Permalink = "Mays-Dennis",
                            Priority = 4,
                            Title = "Violet Clarke"
                        },
                        new
                        {
                            Id = 8,
                            Active = true,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Deserunt nisi sint magna magna ad fugiat esse culpa ipsum cillum ullamco. Minim fugiat duis reprehenderit sint nisi exercitation qui cupidatat duis velit ut in cillum eiusmod. Ea aliquip sunt et qui ea ipsum aliqua minim ex ad culpa ea. Labore qui in tempor eu voluptate duis cupidatat aliqua do veniam dolore Lorem. Labore cupidatat Lorem sunt ad aliquip eiusmod non culpa pariatur ullamco do exercitation sunt minim.\r\n",
                            ModificationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = 3,
                            Permalink = "Lewis-Avila",
                            Priority = 2,
                            Title = "Krystal Johnson"
                        },
                        new
                        {
                            Id = 9,
                            Active = false,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Magna aute adipisicing amet deserunt sint quis dolor mollit nisi officia qui reprehenderit duis occaecat. Consequat sit sit quis dolore sunt nulla cupidatat et tempor consectetur duis labore elit. Aute adipisicing ullamco incididunt fugiat esse aliqua elit velit. Culpa amet aute do velit anim pariatur. Pariatur ex quis ex dolor est qui. Non velit anim et laboris adipisicing nostrud proident do proident mollit elit minim. Occaecat mollit proident nostrud nisi irure ipsum amet incididunt dolore magna ex.\r\n",
                            ModificationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = 4,
                            Permalink = "Kirk-Spence",
                            Priority = 1,
                            Title = "Mack Ross"
                        },
                        new
                        {
                            Id = 10,
                            Active = false,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ullamco cupidatat tempor proident deserunt elit occaecat magna est aute. Aliqua excepteur aliquip anim dolore deserunt irure. Ullamco ex nulla ipsum mollit velit aliqua mollit. Deserunt enim quis tempor est esse pariatur aliquip nulla proident officia ullamco commodo. Fugiat qui ipsum officia non sint. Sit reprehenderit aute Lorem nisi quis aliquip culpa sunt cupidatat.\r\n",
                            ModificationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = 9,
                            Permalink = "Dona-Soto",
                            Priority = 1,
                            Title = "Patel Castaneda"
                        });
                });

            modelBuilder.Entity("Products.Domain.Products.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CoverImageUrl")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("https://via.placeholder.com/150x150.png");

                    b.Property<DateTime>("CreationDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2022, 3, 3, 15, 42, 39, 840, DateTimeKind.Utc).AddTicks(9455));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<DateTime>("ModificationDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2022, 3, 3, 15, 42, 39, 840, DateTimeKind.Utc).AddTicks(9657));

                    b.Property<string>("Permalink")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Products.Domain.Categories.Category", b =>
                {
                    b.HasOne("Products.Domain.Categories.Category", "ParentCategory")
                        .WithMany()
                        .HasForeignKey("ParentCategoryId");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("Products.Domain.Products.Product", b =>
                {
                    b.HasOne("Products.Domain.Categories.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Products.Domain.Categories.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
